### ISSUE TITLE
双拼情况下一些字无法打出来

### ISSUE THREAD

**Issue by fuergaosi233** [wongdean/rime-settings#55]
RIME
![image](https://user-images.githubusercontent.com/22197568/115219081-bfeb2a80-a139-11eb-8643-ddd640dd6f5b.png)
系统自带
![image](https://user-images.githubusercontent.com/22197568/115219156-cf6a7380-a139-11eb-9bf6-7e2d8a3e5ab8.png)

**Comment by wongdean** [comment]
这是什么情况下啊，我打`hc`是没问题的，我没办法复现你这个。。

**Comment by fuergaosi233** [comment]
这个是我的 config 信息 
```yaml
patch:
  schema_list:
    - schema: double_pinyin_flypy # 小鹤双拼
    - schema: luna_pinyin # 全拼
    # - schema: double_pinyin # 自然码
  switcher/hotkeys:
    - "Control+grave" # 注意是control+`，不是command+`
  switcher/save_options:
    - full_shape
    - ascii_punct
    - simplification
    - zh_hans
    - emoji_suggestion
  menu/page_size: 8
  ascii_composer: # 设置caps、shift、control等键的作用
    good_old_caps_lock: true # 若为true，caps只切换大小写
    switch_key:
      Shift_L: commit_code
      Shift_R: noop
      Control_L: noop
      Control_R: noop
      Caps_Lock: commit_code
      Eisu_toggle: clear
```
