### ISSUE TITLE
打字的时候切换“英/中”，默认用鼠须管，可输入时却成了英文字母

### ISSUE THREAD

**Issue by hoochanlon** [wongdean/rime-settings#70]
我用的是Mac系统默认cap lock键来切换中英文的

**Comment by hoochanlon** [comment]
我知道了是静默模式的问题。我在squirrel.custom.yaml设置app_options的选项设置成false就好了。索性一次性关了。

```yaml

  app_options:
    com.github.GitHubClient:
      ascii_mode: false
    com.microsoft.VSCode:
      ascii_mode: false
    com.apple.dt.Xcode:
      ascii_mode: false
    com.runningwithcrayons.Alfred:
      ascii_mode: false
    com.apple.Terminal:
      ascii_mode: false
    com.googlecode.iterm2:
      ascii_mode: false
    com.apple.finder:
      ascii_mode: false
    com.sublimetext.4:
      ascii_mode: false
    com.sublimetext.3:
      ascii_mode: false
    com.apple.calculator:
      ascii_mode: false
    com.apple.launchpad.launcher:
      ascii_mode: false
    com.apple.systempreferences:
      ascii_mode: false
    com.apple.ActivityMonitor:
      ascii_mode: false
    com.apple.keychainaccess:
      ascii_mode: false
    com.apple.Spotlight:
      ascii_mode: false
    com.jetbrains.intellij:
      ascii_mode: false
    com.jetbrains.datagrip:
      ascii_mode: false
    com.jetbrains.pycharm:
      ascii_mode: false
    io.nteract.nteract:
      ascii_mode: false
    com.sequelpro.SequelPro:
      ascii_mode: false
    io.termix.client:
      ascii_mode: false
    com.agilebits.onepassword7:
      ascii_mode: false
    com.agilebits.onepassword7-helper:
      ascii_mode: false
    com.kapeli.dashdoc:
      ascii_mode: false
    com.svend.uPic:
      ascii_mode: false
    com.eusoft.eudic:
      ascii_mode: false    


```
