### ISSUE TITLE
增加跟随系统调整主题（暗黑模式）

### ISSUE THREAD

**Issue by hetaozdh** [wongdean/rime-settings#72]
能否通过修改配置或者脚本实现跟随系统主题自动调整为暗黑模式。

**Comment by wongdean** [comment]
抱歉，这个暂时无法做到，如果要通过第三方脚本切换，势必需要连接Rime和系统的API，暂时没有精力，非常抱歉。这个请求建议去rime主仓库提问

**Comment by wbopan** [comment]
如果是macos的话，鼠须管自带了深浅色切换模式，我的版本是鼠须管0.16.2，只要修改squirrel.custom.yaml
```
# 如果想要修改皮肤，直接更改 color_scheme 的值即可
  style:
    color_scheme: apathy
    color_scheme_dark: mojave_dark
```
`color_scheme_dark`会自动成为系统在深色模式下的主题
